"""Generate snippets/av-wordmark.liquid: inline SVG outlines of the wordmark.

Usage: <venv>/bin/python scripts/build-wordmark.py path/to/montage.otf
Requires fontTools. The OTF is never committed; only the SVG paths are.
Regeneration is deterministic: after re-running against the same OTF,
`git diff snippets/av-wordmark.liquid` must be empty — that is the test.
"""
import sys
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

TEXT = "ANANTA VASTRAM"
TRACKING = 0.18  # em, between the 0.18em (opening) and 0.2em (header/footer) letter-spacing of the text wordmark
OUT = Path(__file__).resolve().parent.parent / "snippets" / "av-wordmark.liquid"


def ntos(v: float) -> str:
    """Round path coordinates to whole font units to keep the snippet small."""
    return str(round(v))


def main(otf: str) -> None:
    font = TTFont(otf)
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    upem = font["head"].unitsPerEm

    for ch in TEXT:
        if ch != " " and ord(ch) not in cmap:
            sys.exit(f"glyph for {ch!r} (U+{ord(ch):04X}) not in {otf}")

    ascent = font["OS/2"].sTypoAscender or font["hhea"].ascent or font["head"].yMax
    descent = abs(font["OS/2"].sTypoDescender or font["hhea"].descent or font["head"].yMin)

    track = TRACKING * upem
    space = font["hmtx"][cmap[ord(" ")]][0] if ord(" ") in cmap else upem * 0.3

    x = 0.0
    paths = []
    for ch in TEXT:
        if ch == " ":
            x += space + track
            continue
        name = cmap[ord(ch)]
        pen = SVGPathPen(glyphs, ntos=ntos)
        # flip y (font y-up -> svg y-down), place at baseline = ascent
        tpen = TransformPen(pen, (1, 0, 0, -1, x, ascent))
        glyphs[name].draw(tpen)
        d = pen.getCommands()
        if d:
            paths.append(f'<path d="{d}"/>')
        x += font["hmtx"][name][0] + track
    width = round(x - track)
    height = ascent + descent

    expected = len(TEXT.replace(" ", ""))
    if len(paths) != expected:
        sys.exit(f"expected {expected} glyph paths, got {len(paths)} — an outline silently dropped")

    svg = (
        f'<svg class="av-wordmark__svg" viewBox="0 0 {width} {height}" '
        f'xmlns="http://www.w3.org/2000/svg" role="img" aria-label="{TEXT.title()}" fill="currentColor">'
        + "".join(paths) + "</svg>"
    )

    liquid = f"""{{%- comment -%}}
  GENERATED by scripts/build-wordmark.py — do not edit by hand.
  Renders the wordmark. Chain: settings.av_logo image if set, else inline Montage SVG outlines.
  Usage: {{% render 'av-wordmark', class: 'av-header__wordmark' %}}
{{%- endcomment -%}}
{{%- if settings.av_logo != blank -%}}
  <span class="{{{{ class | default: 'av-wordmark' }}}}">{{{{ settings.av_logo | image_url: width: 600 | image_tag: alt: shop.name, loading: 'eager' }}}}</span>
{{%- else -%}}
  <span class="{{{{ class | default: 'av-wordmark' }}}} av-wordmark--svg">{svg}</span>
{{%- endif -%}}
"""
    OUT.write_text(liquid, encoding="utf-8")
    print(f"wrote {OUT} ({width}x{height}, {len(paths)} glyph paths)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: build-wordmark.py path/to/montage.otf", file=sys.stderr)
        sys.exit(2)
    main(sys.argv[1])
